[project]
name = "equi2cube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.10.0.84",
    "rerun-sdk>=0.18.2",
    "torch>=2.4.1",
    "torchvision>=0.19.1",
]
