[project]
name = "vis-colmap-sparse-by-rerun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "isort>=5.13.2",
    "numpy>=1.26.4",
    "opencv-python>=4.10.0.84",
    "rerun-sdk>=0.18.2",
]
