[project]
name = "colmap-known-poses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "debugpy>=1.8.6",
    "numpy>=2.1.2",
    "opencv-python>=4.10.0.84",
]
